function talk() {
    var know = {
        "hi": "Hello, how may i help you today!",
        "Hi": "Hello, how may i help you today!",
        "How are you": "Good :)",
        "how are you": "Good :)",
        "What kind of movies are for kids": "Spiderman,Captain marvel,advngers.AKA(Marvel movies)",
        "what kind of movies are for kids": "Spiderman,Captain marvel,advngers.AKA(Marvel movies)",
        "What kind of movies do you have": "Mainly marvel super hero movies",
        "what kind of movies do you have": "Mainly marvel super hero movies",
        "What kind of movies can i watch": "It depends on your age, how old are you",
        "what kind of movies can i watch": "It depends on your age, how old are you",
        "1": "You are too young to be here",
        "2": "You are too young to be here",
        "3": "You are too young to be here",
        "4": "You are too young to be here",
        "5": "Spiderman,Lego Advengers",
        "6": "Spiderman,Lego Advengers",
        "7": "Spiderman,Lego Advengers",
        "8": "Spiderman,Lego Advengers",
        "9": "Spiderman,Lego Advengers",
        "10": "Spiderman,Lego Advengers",
        "11": "Spiderman,Lego Advengers",
        "12": "Captain Marvel, Blue beetle,Spiderman,Lego Advengers,Captain Marvel",
        "13": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "14": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "15": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "16": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "17": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "18": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "19": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "20": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "21": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "22": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "23": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "24": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "25": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "26": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "27": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "28": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "29": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "30": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "31": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "32": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "33": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "34": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "35": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "36": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "37": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "38": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "39": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "40": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "41": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "42": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "43": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "44": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "45": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "46": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "47": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "48": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "49": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "50": "Advengers, Blue beetle, The dark knight(Batman), Immortals of Aveum,Spiderman,Lego Advengers,Captain Marvel,UNDERCOVER,TERMINATOR SALVATION",
        "Bye": "Thank you! Enjoy the website..",
        "bye": "Thank you! Enjoy the website..",
    };
    var user = document.getElementById('userBox').value;
    document.getElementById('chatLog').innerHTML = user + "<br>";
    if (user in know) {
        document.getElementById('chatLog').innerHTML = know[user] + "<br>";
    } else {
        document.getElementById('chatLog').innerHTML = "Sorry,I didn't understand <br>";
    }
}